/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletsIndexRouteImport } from './routes/wallets/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as WalletsAddressRouteImport } from './routes/wallets/$address'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as ContractsContractIdRouteImport } from './routes/contracts/$contractId'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsIndexRoute = WalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsAddressRoute = WalletsAddressRouteImport.update({
  id: '/wallets/$address',
  path: '/wallets/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/contracts/': typeof ContractsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/contracts': typeof ContractsIndexRoute
  '/events': typeof EventsIndexRoute
  '/wallets': typeof WalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/wallets/$address': typeof WalletsAddressRoute
  '/contracts/': typeof ContractsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sync'
    | '/contracts/$contractId'
    | '/events/$eventId'
    | '/wallets/$address'
    | '/contracts/'
    | '/events/'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sync'
    | '/contracts/$contractId'
    | '/events/$eventId'
    | '/wallets/$address'
    | '/contracts'
    | '/events'
    | '/wallets'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sync'
    | '/contracts/$contractId'
    | '/events/$eventId'
    | '/wallets/$address'
    | '/contracts/'
    | '/events/'
    | '/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  WalletsAddressRoute: typeof WalletsAddressRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  WalletsIndexRoute: typeof WalletsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/': {
      id: '/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof WalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/$address': {
      id: '/wallets/$address'
      path: '/wallets/$address'
      fullPath: '/wallets/$address'
      preLoaderRoute: typeof WalletsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  WalletsAddressRoute: WalletsAddressRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  WalletsIndexRoute: WalletsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
